name: Build and Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            gatsby/node_modules/
            gatsby/.cache/
            public/
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') )}}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          cd gatsby
          npm install
          npm install js-yaml

      - name: Fetch catalogs and solutions
        run: node gatsby/fetch-catalogs.js

      - name: Build site
        run: |
          cd gatsby
          ./node_modules/.bin/gatsby build --prefix-paths

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./gatsby/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
